import type { KnipConfig } from 'knip'

const config: KnipConfig = {
  ignore: [
    // shadcn/ui primitives: curated component library, not all exports are consumed yet
    'src/components/ui/**',
    // auto-generated by the TanStack Router plugin
    'src/routeTree.gen.ts',
    // static assets loaded at runtime via script/URL injection (e.g. emotion-ball),
    // not part of the static module graph so Knip cannot see their usage
    'public/**',
  ],
  ignoreDependencies: ['tailwindcss', 'tw-animate-css'],
}

export default config